services:
  db:
    image: postgres:15
    container_name: carbnb-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: carbnb_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbnb-web
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password123@db:5432/carbnb_admin?schema=public
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  postgres_data:
