// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // CLI operations (migrate, db pull, studio) use the direct (session-mode) connection.
    // Falls back to DATABASE_URL if DIRECT_URL isn't set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
